# Generated by Django 4.2 on 2023-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='staff_id',
            field=models.CharField(default='FME/EAD/000', max_length=15),
        ),
    ]
