# Generated by Django 4.2 on 2023-04-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_gis_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="staff_id",
            field=models.CharField(default="FME/EAD/000", max_length=15, unique=True),
        ),
    ]
