# Generated by Django 4.2 on 2023-04-27 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_myuser_staff_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GisStaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("other_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("bio", models.CharField(max_length=100)),
                ("rank", models.CharField(max_length=6)),
                ("department", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
