# Generated by Django 4.2 on 2023-04-29 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_gisstaffprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StaffProfile",
            new_name="Profile",
        ),
        migrations.RemoveField(
            model_name="gisstaffprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Gis_staff",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="role",
        ),
        migrations.DeleteModel(
            name="GisStaffProfile",
        ),
    ]
