# Generated by Django 4.2 on 2023-05-09 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_myuser_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="group",
        ),
    ]
