# Generated by Django 4.2 on 2023-05-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0010_alter_myuser_sign_up_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
