# Generated by Django 4.2 on 2023-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=550)),
                ("file_no", models.IntegerField()),
                (
                    "reg_cat",
                    models.CharField(
                        choices=[
                            ("eia", "EIA"),
                            ("esia", "ESIA"),
                            ("eshia", "ESHIA"),
                            ("emp", "EMP"),
                            ("esmp", "ESMP"),
                            ("eshmp", "eshmp"),
                            ("esmf", "esmf"),
                        ],
                        max_length=8,
                        verbose_name="REGISTRATION TYPE",
                    ),
                ),
            ],
        ),
    ]
