# Generated by Django 4.2 on 2023-05-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bar_codes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="reg_cat",
            field=models.CharField(
                choices=[
                    ("EIA", "EIA"),
                    ("ESIA", "ESIA"),
                    ("ESHIA", "ESHIA"),
                    ("EMP", "EMP"),
                    ("ESMP", "ESMP"),
                    ("ESHMP", "ESHMP"),
                    ("ESMF", "ESMF"),
                ],
                max_length=8,
                verbose_name="REGISTRATION TYPE",
            ),
        ),
    ]
