# Generated by Django 4.2 on 2023-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bar_codes", "0002_alter_project_reg_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="reg_cat",
            field=models.CharField(
                choices=[
                    ("eia", "EIA"),
                    ("esia", "ESIA"),
                    ("eshia", "ESHIA"),
                    ("emp", "EMP"),
                    ("esmp", "ESMP"),
                    ("eshmp", "ESHMP"),
                    ("esmf", "ESMF"),
                    ("rap", "RAP"),
                    ("sea", "SEA"),
                    ("escp", "ESCP"),
                    ("sep", "SEP"),
                    ("lmp", "LMP"),
                    ("rpf", "RPF"),
                    ("grm", "GRM"),
                    ("ipmp", "IPMP"),
                ],
                default=None,
                max_length=8,
            ),
        ),
    ]
